:repository-owner: joeyparrish
:repository-name: Ethernet
:url-arduino-cli: https://arduino.github.io/arduino-cli/0.35/installation/
:url-issue-267: https://github.com/arduino-libraries/Ethernet/issues/267
:url-pr-268: https://github.com/arduino-libraries/Ethernet/pull/268

= {repository-name} Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

With the Arduino Ethernet Shield, this library allows an Arduino board to connect to the internet.

For more information about this library please visit us at
https://www.arduino.cc/en/Reference/{repository-name}

== Fork Information ==

This fork fixes upstream {url-issue-267}[issue #267], in which SPI and socket settings can't be changed without modifying the library.  It does this by incorporating {url-pr-268}[PR #268].

Because the upstream repo seems to be unmaintained (judging by the lack of
activity on issues and PRs), this fork will stand for the foreseeable future.

== Fork Installation Instructions ==

Install `arduino-cli` as detailed in the {url-arduino-cli}[Arduino CLI installation docs].

Then run:

[,sh]
----
   arduino-cli config set library.enable_unsafe_install true
   arduino-cli lib install --git-url https://github.com/joeyparrish/Ethernet
----

== License ==

Copyright (c) 2010 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
